<!doctype html>
<html>
<head>
<title>Lamp 2 Project 1</title>
<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="js/ajax_json.js"></script>
<link rel="stylesheet" href="css/main.css" />
<meta name="viewport" content="width=device-width,initial-scale=1" /> 
</head>
<body>
<div id="wrap">
  <div class="header">
    <div class="header-contents">
      <div class="header-left">
       <p class="header-title">To Do List</p>
      </div>
       <div class="header-right">
       <p class="header-title2">This project is generated by using AJAX and PHP</p>
      </div>
    </div>
  </div>
  <div class="main">
   <div class="main-contents">
    <div class="main-part">
     <form id="project1Form">
     <div class="buttonsLeft">
	    <p class="buttonsTitle">Tasks to display</p> 
      <input type="radio" name="includeCompleted" id="noCompleted"/>Show incomplete only<br/>
      <input type="radio" name="includeCompleted" id="Completed" checked/>Show all<br/>
     </div>
     <div class="buttonsRight">
      <p class="buttonsTitle">Sort Order</p> 
      <input type="radio" name="sortBy" id="dateCreated" checked/>Sort by date created<br/>
      <input type="radio" name="sortBy" id="priority"/>Sort by priority<br/><br/><br/>
     </div>
      <div id="table"></div>

      <input type='submit' id='submitTask2' value='Complete Tasks' class="tranparentButton1"/>
      <input type='submit' id='submitTask3' value='Delete Tasks' class="tranparentButton2"/><br/><br/>

      <p class="buttonsTitle">Add a new task</p>
      <input type='text' id='taskName' name='taskName' class="transparentBox"/>
      <select name='priority' id='priority' class="transparentMenu">
      <option value="1">Very Low</option>
      <option value="2">Low</option>
      <option value="3">Medium</option>
      <option value="4">Important</option>
      <option value="5">Very Important</option>
      </select>
      <input type='submit' id='submitTask' value='Submit' class='tranparentButton3'/>

     </form>
    </div>
   </div>
  </div>
  <br/><br/><br/><br/>
  <div class="footer">
  <p>Ali Nursal &copy; 2017</p>  
  </div>
</div>
</body>
</html>